"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/static-components */
import Image from "next/image";
import { useEffect, useState } from "react";
import { addAssignment, createReview, deleteQuestion, editable, loadData, login, logout, saveAnswers, updateReviewStatus, upsertQuestion, upsertUser } from "@/lib/service";
import { AppData, Assignment, PerformanceReview, Question, QuestionType, Relationship, User } from "@/lib/types";

type View="dashboard"|"users"|"reviews"|"templates"|"mine"|"received"; type Common={data:AppData;refresh:()=>Promise<void>};
const rels:Relationship[]=["SELF","MANAGER","PEER","SUBORDINATE"];
export function PrototypeApp() {
  const [data, setData] = useState<AppData | null>(null);
  const [user, setUser] = useState<User | null>(null);
  const [view, setView] = useState<View>("dashboard");
  const [menu, setMenu] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [loadError, setLoadError] = useState("");

  useEffect(() => {
    loadData().then(({data:d,user:u}) => { setData(d); setUser(u); }).catch(error => setLoadError(error instanceof Error ? error.message : "Unable to load application."));
    setSidebarOpen(sessionStorage.getItem("doki-sidebar-open") !== "false");
  }, []);

  const toggleSidebar = (open: boolean) => {
    setSidebarOpen(open);
    sessionStorage.setItem("doki-sidebar-open", String(open));
  };
  const refresh = async () => { const result=await loadData(); setData(result.data); setUser(result.user); };
  if (loadError) return <main className="grid min-h-screen place-items-center p-4"><div className="card max-w-lg"><h1 className="text-2xl font-black">Unable to connect</h1><p className="mt-3 text-slate-600">{loadError}</p><button className="btn primary mt-5" onClick={() => location.reload()}>Try Again</button></div></main>;
  if (!data) return <main className="grid min-h-screen place-items-center"><span className="font-bold text-slate-500">Loading…</span></main>;
  if (!user) return <Login data={data} done={setUser} />;

  const admin = user.role === "ADMIN";
  const nav = (admin
    ? [["dashboard", "Dashboard"], ["users", "Users"], ["reviews", "Performance Reviews"], ["templates", "Question Templates"]]
    : [["dashboard", "Dashboard"], ["mine", "My Reviews"], ["received", "Reviews About Me"]]) as [View, string][];
  const content = admin
    ? view === "users" ? <Users data={data} refresh={refresh} />
      : view === "reviews" ? <Reviews data={data} refresh={refresh} />
      : view === "templates" ? <Templates data={data} refresh={refresh} />
      : <Dashboard data={data} user={user} />
    : view === "mine" ? <Mine data={data} user={user} refresh={refresh} />
      : view === "received" ? <Received data={data} user={user} />
      : <Dashboard data={data} user={user} />;

  const Side = ({ collapsible = false }: { collapsible?: boolean }) => (
    <aside className="flex h-full flex-col bg-white px-7 py-8">
      <div className="flex items-start justify-between gap-4">
        <Brand sidebar />
        {collapsible && <button className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl border border-slate-200 bg-white text-slate-600 shadow-md shadow-slate-200/60 transition hover:-translate-y-0.5 hover:border-slate-300 hover:text-slate-950" onClick={() => toggleSidebar(false)} aria-label="Collapse sidebar" title="Collapse sidebar"><SidebarCollapseIcon /></button>}
      </div>
      <nav className="mt-10 space-y-2">{nav.map(([k, l]) => <button key={k} onClick={() => { setView(k); setMenu(false); }} className={`block w-full rounded-2xl px-4 py-3 text-left text-sm font-black ${view === k ? "bg-slate-950 text-white" : "hover:bg-slate-100"}`}>{l}</button>)}</nav>
      <div className="mt-auto rounded-3xl bg-slate-950 p-5 text-white"><b>{user.name}</b><p className="mt-1 text-xs uppercase tracking-widest text-slate-400">{user.role} · {user.position}</p><button className="mt-4 w-full rounded-xl bg-white p-2 font-black text-slate-950" onClick={async () => { await logout(); setUser(null); setData(null); location.reload(); }}>Logout</button></div>
    </aside>
  );

  return <main className="min-h-screen">
    <header className="sticky top-0 z-30 flex items-center justify-between bg-white p-4 lg:hidden"><Brand /><button className="btn secondary" onClick={() => setMenu(true)}>☰</button></header>
    {menu && <div className="fixed inset-0 z-50 bg-slate-950/50 lg:hidden" onClick={() => setMenu(false)}><div className="h-full w-80" onClick={e => e.stopPropagation()}><Side /></div></div>}
    <div className="flex">
      <div className={`sticky top-0 hidden h-screen shrink-0 overflow-hidden border-r border-slate-200 transition-[width] duration-300 lg:block ${sidebarOpen ? "w-72" : "w-0"}`}><Side collapsible /></div>
      <section className="min-w-0 flex-1 p-4 sm:p-6 lg:p-8">
        {!sidebarOpen && <button className="mb-5 hidden h-14 w-14 place-items-center rounded-2xl border border-slate-200 bg-white text-slate-600 shadow-md shadow-slate-200/60 transition hover:-translate-y-0.5 hover:border-slate-300 hover:text-slate-950 lg:grid" onClick={() => toggleSidebar(true)} aria-label="Expand sidebar" title="Expand sidebar"><SidebarExpandIcon /></button>}
        {content}
      </section>
    </div>
  </main>;
}
function Brand({ sidebar = false }: { sidebar?: boolean }) {
  if (sidebar) return <div className="min-w-0 pt-1">
    <Image src="/doki-logo-yellow.png" alt="DOKI" width={132} height={50} priority className="h-auto w-[132px]" />
    <h1 className="mt-6 max-w-[150px] text-[1.85rem] font-black leading-[1.08] tracking-[-0.035em] text-slate-950">Performance<br />Review</h1>
  </div>;
  return <div className="flex items-center gap-3"><Image src="/doki-logo-yellow.png" alt="DOKI" width={88} height={33} /><b className="text-sm">Performance Review</b></div>;
}
function SidebarCollapseIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24" className="h-6 w-6" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M9 4v16"/><path d="m15 9-3 3 3 3"/></svg>; }
function SidebarExpandIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24" className="h-6 w-6" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M9 4v16"/><path d="m12 9 3 3-3 3"/></svg>; }
function Login({done}:{data:AppData;done:(u:User)=>void}){const[u,setU]=useState(""),[p,setP]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);return <main className="grid min-h-screen place-items-center p-4"><form className="card w-full max-w-md" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{done(await login(u,p));location.reload()}catch(x){setError((x as Error).message)}finally{setBusy(false)}}}><div className="text-center"><Image className="mx-auto" src="/doki-logo-yellow.png" alt="DOKI" width={160} height={60}/><h1 className="mt-4 text-3xl font-black">Performance Review</h1></div><div className="mt-8 space-y-4"><Field label="Username"><input required autoComplete="username" className="input" value={u} onChange={e=>setU(e.target.value)}/></Field><Field label="Password"><input required autoComplete="current-password" type="password" className="input" value={p} onChange={e=>setP(e.target.value)}/></Field>{error&&<Alert>{error}</Alert>}<button disabled={busy} className="btn primary w-full disabled:opacity-60">{busy?"Signing in…":"Login"}</button></div></form></main>}
function Head({title,text,action}:{title:string;text:string;action?:React.ReactNode}){return <div className="card flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="eyebrow">DOKI Performance Review</p><h1 className="title">{title}</h1><p className="mt-2 text-sm text-slate-500">{text}</p></div>{action}</div>}
function Dashboard({data,user}:{data:AppData;user:User}){const all=data.reviews.flatMap(r=>r.assignments),mine=all.filter(a=>a.reviewerId===user.id),items=user.role==="ADMIN"?all:mine;return <div className="space-y-6"><Head title={user.role==="ADMIN"?"HR Dashboard":`Welcome, ${user.name.split(" ")[0]}`} text="Monitor what is active, complete, and due next."/><div className="metrics"><Metric label="Active cycles" value={data.reviews.filter(r=>r.status!=="CLOSED").length}/><Metric label="Not started" value={items.filter(a=>a.status==="NOT_STARTED").length}/><Metric label="Draft" value={items.filter(a=>a.status==="DRAFT").length}/><Metric label="Submitted" value={items.filter(a=>a.status==="SUBMITTED").length}/></div><div className="card space-y-3"><h2 className="text-xl font-black">Review cycles</h2>{data.reviews.map(r=><div className="rounded-2xl border border-slate-200 p-4" key={r.id}><div className="flex justify-between gap-3"><div><b>{r.title}</b><p className="text-xs text-slate-500">Deadline {date(r.endDate)} · {r.assignments.length} assignments</p></div><Badge v={r.status}/></div></div>)}</div></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="card"><p className="eyebrow">{label}</p><p className="mt-2 text-4xl font-black">{value}</p></div>}
function Users({data,refresh}:Common){const[edit,setEdit]=useState<User|null|undefined>();return <div className="space-y-6"><Head title="Users" text="Manage employee accounts. Historical users should be made inactive." action={<button className="btn primary" onClick={()=>setEdit(null)}>+ Add User</button>}/><div className="table"><table><thead><tr><th>Name</th><th>Position</th><th>Username</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.users.map(u=><tr key={u.id}><td><b>{u.name}</b></td><td>{u.position}</td><td>{u.username}</td><td>{u.role}</td><td><Badge v={u.status}/></td><td><button className="btn secondary small" onClick={()=>setEdit(u)}>Edit</button></td></tr>)}</tbody></table></div>{edit!==undefined&&<UserModal user={edit} data={data} close={()=>setEdit(undefined)} done={()=>{setEdit(undefined);refresh()}}/>}</div>}
function UserModal({user,data,close,done}:{user:User|null;data:AppData;close:()=>void;done:()=>void}){const[f,setF]=useState({name:user?.name||"",position:user?.position||"",username:user?.username||"",password:"",role:user?.role||"USER",status:user?.status||"ACTIVE"}),[error,setError]=useState("");return <Modal title={user?"Edit User":"Add User"} close={close}><form className="grid gap-4 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();try{await upsertUser(data,{...f,id:user?.id,role:f.role as User["role"],status:f.status as User["status"]});done()}catch(x){setError((x as Error).message)}}}>{(["name","position","username","password"]as const).map(k=><Field key={k} label={k==="password"&&user?"New Password (optional)":k[0].toUpperCase()+k.slice(1)}><input required={k!=="password"||!user} type={k==="password"?"password":"text"} className="input" value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></Field>)}<Field label="Role"><select className="input" value={f.role} onChange={e=>setF({...f,role:e.target.value as User["role"]})}><option>USER</option><option>ADMIN</option></select></Field><Field label="Status"><select className="input" value={f.status} onChange={e=>setF({...f,status:e.target.value as User["status"]})}><option>ACTIVE</option><option>INACTIVE</option></select></Field>{error&&<Alert>{error}</Alert>}<Actions close={close} label="Save User"/></form></Modal>}
function Templates({data,refresh}:Common){const[rel,setRel]=useState<Relationship>("SELF"),[edit,setEdit]=useState<Question|null|undefined>();const list=[...data.templates[rel]].sort((a,b)=>a.order-b.order);return <div className="space-y-6"><Head title="Question Templates" text="Reusable starting points. Existing review snapshots never change." action={<button className="btn primary" onClick={()=>setEdit(null)}>+ Add Question</button>}/><div className="flex gap-2 overflow-auto rounded-2xl bg-white p-2">{rels.map(r=><button className={`btn small ${rel===r?"primary":""}`} key={r} onClick={()=>setRel(r)}>{r}</button>)}</div><div className="card space-y-3">{list.map((q,i)=><div key={q.id} className="flex items-center gap-3 rounded-2xl border p-4"><b>{i+1}</b><div className="flex-1"><b>{q.text}</b><p className="eyebrow mt-1">{q.type}</p></div><button className="btn secondary small" onClick={()=>setEdit(q)}>Edit</button><button className="text-xs font-black text-rose-700" onClick={async()=>{if(confirm("Delete this question?")){await deleteQuestion(q.id);await refresh()}}}>Delete</button></div>)}</div>{edit!==undefined&&<QuestionModal q={edit} rel={rel} close={()=>setEdit(undefined)} done={async(text,type)=>{await upsertQuestion(data,rel,{id:edit?.id,order:edit?.order,text,type});setEdit(undefined);await refresh()}}/>}</div>}
function QuestionModal({q,rel,close,done}:{q:Question|null;rel:Relationship;close:()=>void;done:(t:string,y:QuestionType)=>Promise<void>}){const[t,setT]=useState(q?.text||""),[y,setY]=useState<QuestionType>(q?.type||"RATING_1_5");return <Modal title={`${q?"Edit":"Add"} ${rel} Question`} close={close}><form className="space-y-4" onSubmit={async e=>{e.preventDefault();await done(t,y)}}><Field label="Question"><textarea required className="input min-h-28" value={t} onChange={e=>setT(e.target.value)}/></Field><Field label="Type"><select className="input" value={y} onChange={e=>setY(e.target.value as QuestionType)}><option>RATING_1_5</option><option>ESSAY</option></select></Field><Actions close={close} label="Save Question"/></form></Modal>}
function Reviews({data,refresh}:Common){const[create,setCreate]=useState(false),[selected,setSelected]=useState<PerformanceReview|null>(null);const reload=async()=>{const result=await loadData();await refresh();setSelected(result.data.reviews.find(r=>r.id===selected?.id)||null)};return <div className="space-y-6"><Head title="Performance Reviews" text="Create cycles, assign relationships, and monitor completion." action={<button className="btn primary" onClick={()=>setCreate(true)}>+ Create Review</button>}/><div className="table"><table><thead><tr><th>Review</th><th>Dates</th><th>Status</th><th>Progress</th><th>Action</th></tr></thead><tbody>{data.reviews.map(r=><tr key={r.id}><td><b>{r.title}</b><p className="text-xs text-slate-500">{r.description}</p></td><td>{date(r.startDate)} – {date(r.endDate)}</td><td><Badge v={r.status}/></td><td>{r.assignments.filter(a=>a.status==="SUBMITTED").length}/{r.assignments.length}</td><td><button className="btn secondary small" onClick={()=>setSelected(r)}>Configure</button></td></tr>)}</tbody></table></div>{create&&<Create data={data} close={()=>setCreate(false)} done={async()=>{setCreate(false);await refresh()}}/>}{selected&&<ReviewModal review={selected} data={data} close={()=>setSelected(null)} done={reload}/>}</div>}
function Create({data,close,done}:{data:AppData;close:()=>void;done:()=>Promise<void>}){const[f,setF]=useState({title:"",description:"",startDate:"",endDate:""}),[ids,setIds]=useState<string[]>([]),[error,setError]=useState("");return <Modal title="Create Performance Review" close={close} wide><form className="space-y-5" onSubmit={async e=>{e.preventDefault();try{await createReview(data,f,ids);await done()}catch(x){setError((x as Error).message)}}}><div className="grid gap-4 sm:grid-cols-2"><Field label="Title"><input required className="input" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></Field><Field label="Description"><input required className="input" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></Field><Field label="Start Date"><input required type="date" className="input" value={f.startDate} onChange={e=>setF({...f,startDate:e.target.value})}/></Field><Field label="End Date / Deadline"><input required type="date" className="input" value={f.endDate} onChange={e=>setF({...f,endDate:e.target.value})}/></Field></div><fieldset><legend className="font-bold">Reviewees — Self assignments are automatic</legend><div className="mt-3 grid gap-2 sm:grid-cols-2">{data.users.filter(u=>u.role==="USER"&&u.status==="ACTIVE").map(u=><label className="rounded-2xl border p-3" key={u.id}><input type="checkbox" className="mr-3" checked={ids.includes(u.id)} onChange={e=>setIds(e.target.checked?[...ids,u.id]:ids.filter(x=>x!==u.id))}/><b>{u.name}</b></label>)}</div></fieldset>{error&&<Alert>{error}</Alert>}<Actions close={close} label="Create Review"/></form></Modal>}
function ReviewModal({review,data,close,done}:{review:PerformanceReview;data:AppData;close:()=>void;done:()=>Promise<void>}){const[add,setAdd]=useState(false);return <Modal title={review.title} close={close} wide><div className="space-y-6"><div className="flex items-center gap-3"><Badge v={review.status}/><span className="text-sm text-slate-500">{date(review.startDate)} – {date(review.endDate)}</span><select className="input ml-auto w-auto" value={review.status} onChange={async e=>{await updateReviewStatus(review.id,e.target.value as PerformanceReview["status"]);await done()}}><option>OPEN</option><option>IN_PROGRESS</option><option>CLOSED</option></select></div><div><div className="flex justify-between"><h3 className="text-xl font-black">Assignments</h3><button className="btn secondary small" onClick={()=>setAdd(true)}>+ Add Reviewer</button></div><div className="mt-3 space-y-2">{review.assignments.map(a=><Row key={a.id} a={a} r={review} data={data}/>)}</div></div><div><h3 className="text-xl font-black">Question snapshot</h3>{review.status!=="OPEN"&&<p className="mt-2 rounded-2xl bg-amber-50 p-3 text-sm font-bold text-amber-800">Questions are locked because this review has started.</p>}<div className="mt-3 grid grid-cols-2 gap-3">{rels.map(x=><div className="rounded-2xl border p-3" key={x}><b>{x}</b><p className="text-sm text-slate-500">{review.questions.filter(q=>q.relationship===x).length} questions</p></div>)}</div></div>{add&&<AssignmentModal review={review} data={data} close={()=>setAdd(false)} done={async()=>{setAdd(false);await done()}}/>}</div></Modal>}
function AssignmentModal({review,data,close,done}:{review:PerformanceReview;data:AppData;close:()=>void;done:()=>Promise<void>}){const ees=[...new Set(review.assignments.map(a=>a.revieweeId))],[ee,setEe]=useState(ees[0]||""),[er,setEr]=useState(""),[rel,setRel]=useState<Exclude<Relationship,"SELF">>("PEER"),[error,setError]=useState("");return <Modal title="Add Reviewer" close={close}><form className="space-y-4" onSubmit={async e=>{e.preventDefault();try{await addAssignment(data,review.id,ee,er,rel);await done()}catch(x){setError((x as Error).message)}}}><Field label="Reviewee"><select className="input" value={ee} onChange={e=>setEe(e.target.value)}>{ees.map(x=><option key={x} value={x}>{who(data,x)}</option>)}</select></Field><Field label="Reviewer"><select required className="input" value={er} onChange={e=>setEr(e.target.value)}><option value="">Select reviewer</option>{data.users.filter(u=>u.status==="ACTIVE"&&u.id!==ee).map(u=><option key={u.id} value={u.id}>{u.name} · {u.position}</option>)}</select></Field><Field label="Relationship"><select className="input" value={rel} onChange={e=>setRel(e.target.value as typeof rel)}><option>MANAGER</option><option>PEER</option><option>SUBORDINATE</option></select></Field>{error&&<Alert>{error}</Alert>}<Actions close={close} label="Add Reviewer"/></form></Modal>}
function Mine({data,user,refresh}:Common&{user:User}){const[open,setOpen]=useState<{a:Assignment;r:PerformanceReview}|null>(null),rows=data.reviews.flatMap(r=>r.assignments.filter(a=>a.reviewerId===user.id).map(a=>({a,r})));return <div className="space-y-6"><Head title="My Reviews" text="Drafts may be incomplete. Submitted reviews stay editable until the deadline."/><div className="card space-y-3">{rows.map(x=><button className="w-full text-left" key={x.a.id} onClick={()=>setOpen(x)}><Row {...x} data={data}/></button>)}</div>{open&&<ReviewForm {...open} data={data} close={()=>setOpen(null)} done={async()=>{await refresh();setOpen(null)}}/>}</div>}
function ReviewForm({a,r,data,close,done}:{a:Assignment;r:PerformanceReview;data:AppData;close:()=>void;done:()=>Promise<void>}){const qs=r.questions.filter(q=>q.relationship===a.relationship).sort((x,y)=>x.order-y.order),[answers,setAnswers]=useState({...a.answers}),[missing,setMissing]=useState<string[]>([]),[error,setError]=useState(""),can=editable(r);const persist=async(submit:boolean)=>{const m=qs.filter(q=>!String(answers[q.id]??"").trim()).map(q=>q.id);if(submit&&m.length){setMissing(m);return}try{await saveAnswers(a.id,answers,submit);await done()}catch(x){setError((x as Error).message)}};return <Modal title={`Review: ${who(data,a.revieweeId)}`} close={close} wide><div className="space-y-4"><div className="flex gap-2"><Badge v={a.relationship}/><Badge v={a.status}/></div>{!can&&<Alert>This review is read-only because it has not started, is closed, or the deadline passed.</Alert>}{error&&<Alert>{error}</Alert>}{qs.map((q,i)=><div className={`rounded-3xl border p-5 ${missing.includes(q.id)?"border-rose-400 bg-rose-50":""}`} key={q.id}><b>{i+1}. {q.text}</b>{q.type==="RATING_1_5"?<div className="mt-4 grid grid-cols-5 gap-2">{[1,2,3,4,5].map(n=><label className={`rounded-xl border p-3 text-center font-black ${answers[q.id]===n?"bg-slate-950 text-white":""}`} key={n}><input disabled={!can} className="sr-only" type="radio" name={q.id} checked={answers[q.id]===n} onChange={()=>setAnswers({...answers,[q.id]:n})}/>{n}</label>)}</div>:<textarea disabled={!can} className="input mt-4 min-h-28" value={String(answers[q.id]??"")} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})}/>}</div>)}{can&&<div className="flex justify-end gap-3"><button className="btn secondary" onClick={()=>persist(false)}>Save Draft</button><button className="btn primary" onClick={()=>{if(confirm("Submit this review? You can still edit it until the deadline."))persist(true)}}>Submit Review</button></div>}</div></Modal>}
function Received({data,user}:{data:AppData;user:User}){const reviews=data.reviews.filter(r=>r.assignments.some(a=>a.revieweeId===user.id));return <div className="space-y-6"><Head title="Reviews About Me" text="Incoming answers appear only after HR closes the review cycle."/>{reviews.map(r=><div className="card" key={r.id}><div className="flex justify-between"><h2 className="text-xl font-black">{r.title}</h2><Badge v={r.status}/></div>{r.status!=="CLOSED"?<p className="mt-5 rounded-2xl bg-slate-50 p-6 text-center text-sm text-slate-500">Results will be available after the Performance Review is closed.</p>:<div className="mt-5 space-y-4">{r.assignments.filter(a=>a.revieweeId===user.id&&a.status==="SUBMITTED").map(a=><div className="rounded-2xl border p-4" key={a.id}><Badge v={a.relationship}/><b className="ml-2">From {who(data,a.reviewerId)}</b>{r.questions.filter(q=>q.relationship===a.relationship).map(q=><div className="mt-3" key={q.id}><p className="text-sm font-bold text-slate-500">{q.text}</p><p>{a.answers[q.id]??"—"}{q.type==="RATING_1_5"?" / 5":""}</p></div>)}</div>)}</div>}</div>)}</div>}
function Row({a,r,data}:{a:Assignment;r:PerformanceReview;data:AppData}){return <div className="flex flex-col gap-2 rounded-2xl border bg-white p-4 sm:flex-row sm:items-center"><div className="flex-1"><b>{who(data,a.revieweeId)}</b><p className="text-xs text-slate-500">{r.title} · Due {date(r.endDate)}</p></div><div className="flex gap-2"><Badge v={a.relationship}/><Badge v={a.status}/></div></div>}
function Badge({v}:{v:string}){const c=["ACTIVE","SUBMITTED","IN_PROGRESS"].includes(v)?"bg-emerald-100 text-emerald-700":["OPEN","DRAFT"].includes(v)?"bg-amber-100 text-amber-800":"bg-slate-200 text-slate-700";return <span className={`rounded-full px-3 py-1 text-[11px] font-black ${c}`}>{v.replaceAll("_"," ")}</span>}
function Modal({title,close,wide,children}:{title:string;close:()=>void;wide?:boolean;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div className={`max-h-[92vh] w-full overflow-auto rounded-[2rem] bg-white p-6 shadow-2xl ${wide?"max-w-4xl":"max-w-xl"}`}><div className="mb-6 flex justify-between"><h2 className="text-2xl font-black">{title}</h2><button className="btn secondary small" onClick={close}>Close</button></div>{children}</div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-2 block text-sm font-bold">{label}</span>{children}</label>}
function Actions({close,label}:{close:()=>void;label:string}){return <div className="flex justify-end gap-3 sm:col-span-2"><button type="button" className="btn secondary" onClick={close}>Cancel</button><button className="btn primary">{label}</button></div>}
function Alert({children}:{children:React.ReactNode}){return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-3 text-sm font-bold text-rose-700">{children}</div>}
const who=(d:AppData,id:string)=>d.users.find(u=>u.id===id)?.name||"Unknown";const date=(v:string)=>new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric"}).format(new Date(v));
