BEGIN;

-- =========================================================
-- PERFORMANCE REVIEW SYSTEM - V1
-- PostgreSQL / Neon
-- =========================================================


-- =========================================================
-- 1. USERS
-- =========================================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(150) NOT NULL,
    position VARCHAR(150) NOT NULL,
    username VARCHAR(100) NOT NULL,
    password_hash TEXT NOT NULL,

    role VARCHAR(20) NOT NULL DEFAULT 'USER'
        CHECK (role IN ('ADMIN', 'USER')),

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'INACTIVE')),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Username case-insensitive.
-- "admin" dan "ADMIN" dianggap username yang sama.
CREATE UNIQUE INDEX uq_users_username_lower
    ON users (LOWER(username));

CREATE INDEX idx_users_status
    ON users (status);

CREATE INDEX idx_users_role
    ON users (role);



-- =========================================================
-- 2. QUESTION TEMPLATES
-- Template dasar berdasarkan relationship.
-- =========================================================

CREATE TABLE question_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(150) NOT NULL,

    relationship_type VARCHAR(30) NOT NULL
        CHECK (
            relationship_type IN (
                'SELF',
                'MANAGER',
                'PEER',
                'SUBORDINATE'
            )
        ),

    description TEXT,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- V1: satu template utama untuk masing-masing hubungan.
    CONSTRAINT uq_question_templates_relationship
        UNIQUE (relationship_type)
);



-- =========================================================
-- 3. TEMPLATE QUESTIONS
-- Pertanyaan yang ada di master template.
-- =========================================================

CREATE TABLE template_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    template_id BIGINT NOT NULL
        REFERENCES question_templates(id)
        ON DELETE CASCADE,

    question_text TEXT NOT NULL,

    question_type VARCHAR(30) NOT NULL
        CHECK (
            question_type IN (
                'RATING_1_5',
                'ESSAY'
            )
        ),

    sort_order INTEGER NOT NULL
        CHECK (sort_order > 0),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_template_questions_template
    ON template_questions(template_id, sort_order);



-- =========================================================
-- 4. PERFORMANCE REVIEWS
-- Master dari setiap Performance Review.
-- =========================================================

CREATE TABLE performance_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title VARCHAR(255) NOT NULL,
    description TEXT,

    -- Absolute timestamps. Display timezone is handled by the client.
    -- Review activity is allowed when:
    -- start_at <= database_time < end_at
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,

    status VARCHAR(30) NOT NULL DEFAULT 'OPEN'
        CHECK (
            status IN (
                'OPEN',
                'IN_PROGRESS',
                'CLOSED'
            )
        ),

    created_by BIGINT NOT NULL
        REFERENCES users(id)
        ON DELETE RESTRICT,

    closed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_performance_review_dates
        CHECK (end_at > start_at)
);

CREATE INDEX idx_performance_reviews_status
    ON performance_reviews(status);

CREATE INDEX idx_performance_reviews_dates
    ON performance_reviews(start_at, end_at);



-- =========================================================
-- 5. PERFORMANCE REVIEW QUESTIONS
--
-- Snapshot pertanyaan.
--
-- Template hanya sumber awal.
-- Begitu review dibuat, pertanyaan disalin ke sini.
--
-- Perubahan template di masa depan TIDAK mengubah review lama.
-- =========================================================

CREATE TABLE performance_review_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    performance_review_id BIGINT NOT NULL
        REFERENCES performance_reviews(id)
        ON DELETE RESTRICT,

    relationship_type VARCHAR(30) NOT NULL
        CHECK (
            relationship_type IN (
                'SELF',
                'MANAGER',
                'PEER',
                'SUBORDINATE'
            )
        ),

    question_text TEXT NOT NULL,

    question_type VARCHAR(30) NOT NULL
        CHECK (
            question_type IN (
                'RATING_1_5',
                'ESSAY'
            )
        ),

    sort_order INTEGER NOT NULL
        CHECK (sort_order > 0),

    -- Hanya untuk trace asal template.
    -- Snapshot text/type tetap tersimpan di tabel ini.
    source_template_question_id BIGINT
        REFERENCES template_questions(id)
        ON DELETE SET NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_review_questions_review_relationship
    ON performance_review_questions(
        performance_review_id,
        relationship_type,
        sort_order
    );



-- =========================================================
-- 6. REVIEW ASSIGNMENTS
--
-- Menentukan:
-- siapa menilai siapa,
-- dan hubungannya apa.
-- =========================================================

CREATE TABLE review_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    performance_review_id BIGINT NOT NULL
        REFERENCES performance_reviews(id)
        ON DELETE RESTRICT,

    reviewer_user_id BIGINT NOT NULL
        REFERENCES users(id)
        ON DELETE RESTRICT,

    reviewee_user_id BIGINT NOT NULL
        REFERENCES users(id)
        ON DELETE RESTRICT,

    relationship_type VARCHAR(30) NOT NULL
        CHECK (
            relationship_type IN (
                'SELF',
                'MANAGER',
                'PEER',
                'SUBORDINATE'
            )
        ),

    status VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED'
        CHECK (
            status IN (
                'NOT_STARTED',
                'DRAFT',
                'SUBMITTED'
            )
        ),

    started_at TIMESTAMPTZ,
    submitted_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Reviewer tidak boleh dua kali menilai orang yang sama
    -- dalam Performance Review yang sama.
    CONSTRAINT uq_review_assignment
        UNIQUE (
            performance_review_id,
            reviewer_user_id,
            reviewee_user_id
        ),

    -- SELF harus dirinya sendiri.
    -- Selain SELF tidak boleh dirinya sendiri.
    CONSTRAINT chk_review_assignment_relationship
        CHECK (
            (
                relationship_type = 'SELF'
                AND reviewer_user_id = reviewee_user_id
            )
            OR
            (
                relationship_type <> 'SELF'
                AND reviewer_user_id <> reviewee_user_id
            )
        ),

    -- Kalau sudah SUBMITTED, submitted_at harus ada.
    CONSTRAINT chk_review_assignment_submission
        CHECK (
            status <> 'SUBMITTED'
            OR submitted_at IS NOT NULL
        )
);

CREATE INDEX idx_review_assignments_review
    ON review_assignments(performance_review_id);

CREATE INDEX idx_review_assignments_reviewer
    ON review_assignments(reviewer_user_id);

CREATE INDEX idx_review_assignments_reviewee
    ON review_assignments(reviewee_user_id);

CREATE INDEX idx_review_assignments_status
    ON review_assignments(status);



-- =========================================================
-- 7. REVIEW ANSWERS
-- =========================================================

CREATE TABLE review_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    review_assignment_id BIGINT NOT NULL
        REFERENCES review_assignments(id)
        ON DELETE RESTRICT,

    review_question_id BIGINT NOT NULL
        REFERENCES performance_review_questions(id)
        ON DELETE RESTRICT,

    rating_value SMALLINT,

    essay_value TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Satu pertanyaan hanya boleh punya satu jawaban
    -- untuk sebuah assignment.
    CONSTRAINT uq_review_answer
        UNIQUE (
            review_assignment_id,
            review_question_id
        ),

    CONSTRAINT chk_review_answer_rating
        CHECK (
            rating_value IS NULL
            OR rating_value BETWEEN 1 AND 5
        ),

    -- Satu row jawaban harus rating ATAU essay.
    CONSTRAINT chk_review_answer_value
        CHECK (
            (
                rating_value IS NOT NULL
                AND essay_value IS NULL
            )
            OR
            (
                rating_value IS NULL
                AND essay_value IS NOT NULL
                AND LENGTH(BTRIM(essay_value)) > 0
            )
        )
);

CREATE INDEX idx_review_answers_assignment
    ON review_answers(review_assignment_id);

CREATE INDEX idx_review_answers_question
    ON review_answers(review_question_id);



-- =========================================================
-- AUTO UPDATED_AT
-- =========================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


CREATE TRIGGER trg_question_templates_updated_at
BEFORE UPDATE ON question_templates
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


CREATE TRIGGER trg_template_questions_updated_at
BEFORE UPDATE ON template_questions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


CREATE TRIGGER trg_performance_reviews_updated_at
BEFORE UPDATE ON performance_reviews
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


CREATE TRIGGER trg_performance_review_questions_updated_at
BEFORE UPDATE ON performance_review_questions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


CREATE TRIGGER trg_review_assignments_updated_at
BEFORE UPDATE ON review_assignments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


CREATE TRIGGER trg_review_answers_updated_at
BEFORE UPDATE ON review_answers
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();



-- =========================================================
-- PERFORMANCE REVIEW STATUS FROM DATABASE TIME
--
-- Source of truth:
-- PostgreSQL database time, NOT browser/device time.
--
-- Rules:
-- database_time < start_at
--     -> OPEN
--
-- start_at <= database_time < end_at
--     -> IN_PROGRESS
--
-- database_time >= end_at
--     -> CLOSED
--
-- end_at is exclusive for review activity/submission.
--
-- closed_at:
-- CLOSED
--     -> end_at
--
-- OPEN / IN_PROGRESS
--     -> NULL
-- =========================================================

CREATE OR REPLACE FUNCTION set_performance_review_status_from_schedule()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_database_time TIMESTAMPTZ := statement_timestamp();
BEGIN

    IF v_database_time >= NEW.end_at THEN
        NEW.status = 'CLOSED';
        NEW.closed_at = NEW.end_at;

    ELSIF v_database_time >= NEW.start_at THEN
        NEW.status = 'IN_PROGRESS';
        NEW.closed_at = NULL;

    ELSE
        NEW.status = 'OPEN';
        NEW.closed_at = NULL;
    END IF;

    RETURN NEW;
END;
$$;


CREATE TRIGGER trg_performance_review_status_from_schedule
BEFORE INSERT OR UPDATE OF start_at, end_at
ON performance_reviews
FOR EACH ROW
EXECUTE FUNCTION set_performance_review_status_from_schedule();



-- =========================================================
-- SYNC PERFORMANCE REVIEW STATUSES
--
-- Neon may Scale to Zero when inactive.
-- There is intentionally no pg_cron/background scheduler.
--
-- The application calls:
--
-- SELECT public.sync_performance_review_statuses();
--
-- before reading Performance Review data.
--
-- This updates only rows whose physical status/closed_at
-- no longer matches the current database time.
-- =========================================================

CREATE OR REPLACE FUNCTION sync_performance_review_statuses()
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_database_time TIMESTAMPTZ := statement_timestamp();
    v_updated_rows INTEGER;
BEGIN

    UPDATE performance_reviews
    SET
        status = CASE
            WHEN v_database_time >= end_at
                THEN 'CLOSED'

            WHEN v_database_time >= start_at
                THEN 'IN_PROGRESS'

            ELSE 'OPEN'
        END,

        closed_at = CASE
            WHEN v_database_time >= end_at
                THEN end_at

            ELSE NULL
        END

    WHERE
        status IS DISTINCT FROM (
            CASE
                WHEN v_database_time >= end_at
                    THEN 'CLOSED'

                WHEN v_database_time >= start_at
                    THEN 'IN_PROGRESS'

                ELSE 'OPEN'
            END
        )
        OR
        closed_at IS DISTINCT FROM (
            CASE
                WHEN v_database_time >= end_at
                    THEN end_at

                ELSE NULL
            END
        );

    GET DIAGNOSTICS v_updated_rows = ROW_COUNT;

    RETURN v_updated_rows;
END;
$$;



-- =========================================================
-- LOCK PERFORMANCE REVIEW QUESTIONS
--
-- Pertanyaan review hanya boleh diubah sebelum review dimulai.
-- =========================================================

CREATE OR REPLACE FUNCTION guard_performance_review_questions()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_review_id BIGINT;
    v_status VARCHAR(30);
    v_start_at TIMESTAMPTZ;
BEGIN

    v_review_id :=
        CASE
            WHEN TG_OP = 'DELETE'
                THEN OLD.performance_review_id
            ELSE NEW.performance_review_id
        END;

    SELECT status, start_at
    INTO v_status, v_start_at
    FROM performance_reviews
    WHERE id = v_review_id;

    -- Admin deletion removes the immutable snapshot together with its review.
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    IF v_status IS NULL THEN
        RAISE EXCEPTION 'Performance Review not found.';
    END IF;

    -- Deleting a template only clears this optional provenance field through
    -- its foreign key. It does not change the historical question snapshot.
    IF TG_OP = 'UPDATE'
       AND NEW.source_template_question_id IS DISTINCT FROM OLD.source_template_question_id
       AND NEW.performance_review_id = OLD.performance_review_id
       AND NEW.relationship_type = OLD.relationship_type
       AND NEW.question_text = OLD.question_text
       AND NEW.question_type = OLD.question_type
       AND NEW.sort_order = OLD.sort_order
    THEN
        RETURN NEW;
    END IF;

    IF v_status <> 'OPEN'
       OR NOW() >= v_start_at
    THEN
        RAISE EXCEPTION
            'Questions cannot be modified after the Performance Review has started.';
    END IF;

    RETURN NEW;
END;
$$;


CREATE TRIGGER trg_guard_review_questions
BEFORE INSERT OR UPDATE OR DELETE
ON performance_review_questions
FOR EACH ROW
EXECUTE FUNCTION guard_performance_review_questions();



-- =========================================================
-- VALIDATE ANSWER AGAINST ASSIGNMENT + QUESTION
--
-- Menjaga:
-- 1. question dan assignment harus berasal dari review sama
-- 2. relationship harus sama
-- 3. rating question hanya menerima rating
-- 4. essay question hanya menerima essay
-- =========================================================

CREATE OR REPLACE FUNCTION validate_review_answer()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_assignment_review_id BIGINT;
    v_assignment_relationship VARCHAR(30);

    v_question_review_id BIGINT;
    v_question_relationship VARCHAR(30);
    v_question_type VARCHAR(30);
BEGIN

    SELECT
        performance_review_id,
        relationship_type
    INTO
        v_assignment_review_id,
        v_assignment_relationship
    FROM review_assignments
    WHERE id = NEW.review_assignment_id;

    IF v_assignment_review_id IS NULL THEN
        RAISE EXCEPTION 'Review assignment not found.';
    END IF;


    SELECT
        performance_review_id,
        relationship_type,
        question_type
    INTO
        v_question_review_id,
        v_question_relationship,
        v_question_type
    FROM performance_review_questions
    WHERE id = NEW.review_question_id;

    IF v_question_review_id IS NULL THEN
        RAISE EXCEPTION 'Review question not found.';
    END IF;


    IF v_assignment_review_id <> v_question_review_id THEN
        RAISE EXCEPTION
            'Question does not belong to the same Performance Review.';
    END IF;


    IF v_assignment_relationship <> v_question_relationship THEN
        RAISE EXCEPTION
            'Question relationship does not match assignment relationship.';
    END IF;


    IF v_question_type = 'RATING_1_5' THEN

        IF NEW.rating_value IS NULL
           OR NEW.essay_value IS NOT NULL
        THEN
            RAISE EXCEPTION
                'Rating question requires rating_value only.';
        END IF;

    ELSIF v_question_type = 'ESSAY' THEN

        IF NEW.essay_value IS NULL
           OR LENGTH(BTRIM(NEW.essay_value)) = 0
           OR NEW.rating_value IS NOT NULL
        THEN
            RAISE EXCEPTION
                'Essay question requires essay_value only.';
        END IF;

    END IF;


    RETURN NEW;
END;
$$;


CREATE TRIGGER trg_validate_review_answer
BEFORE INSERT OR UPDATE
ON review_answers
FOR EACH ROW
EXECUTE FUNCTION validate_review_answer();



-- =========================================================
-- COPY TEMPLATE QUESTIONS INTO PERFORMANCE REVIEW
--
-- Snapshot template -> actual review questions
--
-- Digunakan saat HR menyiapkan review.
-- =========================================================

CREATE OR REPLACE FUNCTION copy_templates_to_performance_review(
    p_performance_review_id BIGINT
)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_existing INTEGER;
    v_inserted INTEGER;
BEGIN

    IF NOT EXISTS (
        SELECT 1
        FROM performance_reviews
        WHERE id = p_performance_review_id
    ) THEN
        RAISE EXCEPTION
            'Performance Review % does not exist.',
            p_performance_review_id;
    END IF;


    SELECT COUNT(*)
    INTO v_existing
    FROM performance_review_questions
    WHERE performance_review_id = p_performance_review_id;


    IF v_existing > 0 THEN
        RAISE EXCEPTION
            'Performance Review already has questions.';
    END IF;


    INSERT INTO performance_review_questions (
        performance_review_id,
        relationship_type,
        question_text,
        question_type,
        sort_order,
        source_template_question_id
    )
    SELECT
        p_performance_review_id,
        qt.relationship_type,
        tq.question_text,
        tq.question_type,
        tq.sort_order,
        tq.id
    FROM question_templates qt
    JOIN template_questions tq
        ON tq.template_id = qt.id
    WHERE qt.is_active = TRUE
    ORDER BY
        qt.relationship_type,
        tq.sort_order;


    GET DIAGNOSTICS v_inserted = ROW_COUNT;

    RETURN v_inserted;
END;
$$;



-- =========================================================
-- VIEW: REVIEW ASSIGNMENT PROGRESS
--
-- Memudahkan:
-- 7 / 10 answered
-- 70%
-- =========================================================

CREATE VIEW v_review_assignment_progress AS
SELECT
    ra.id AS review_assignment_id,

    ra.performance_review_id,

    pr.title AS performance_review_title,
    pr.start_at,
    pr.end_at,
    pr.status AS performance_review_status,

    ra.reviewer_user_id,
    reviewer.name AS reviewer_name,

    ra.reviewee_user_id,
    reviewee.name AS reviewee_name,

    ra.relationship_type,

    ra.status AS assignment_status,

    COUNT(DISTINCT prq.id) AS total_questions,

    COUNT(DISTINCT ans.review_question_id)
        AS answered_questions,

    CASE
        WHEN COUNT(DISTINCT prq.id) = 0
            THEN 0

        ELSE ROUND(
            (
                COUNT(DISTINCT ans.review_question_id)::NUMERIC
                /
                COUNT(DISTINCT prq.id)::NUMERIC
            ) * 100,
            2
        )
    END AS completion_percentage,

    ra.started_at,
    ra.submitted_at,
    ra.updated_at

FROM review_assignments ra

JOIN performance_reviews pr
    ON pr.id = ra.performance_review_id

JOIN users reviewer
    ON reviewer.id = ra.reviewer_user_id

JOIN users reviewee
    ON reviewee.id = ra.reviewee_user_id

LEFT JOIN performance_review_questions prq
    ON prq.performance_review_id = ra.performance_review_id
    AND prq.relationship_type = ra.relationship_type

LEFT JOIN review_answers ans
    ON ans.review_assignment_id = ra.id
    AND ans.review_question_id = prq.id

GROUP BY
    ra.id,
    ra.performance_review_id,

    pr.title,
    pr.start_at,
    pr.end_at,
    pr.status,

    ra.reviewer_user_id,
    reviewer.name,

    ra.reviewee_user_id,
    reviewee.name,

    ra.relationship_type,
    ra.status,

    ra.started_at,
    ra.submitted_at,
    ra.updated_at;



-- =========================================================
-- VIEW: PERFORMANCE REVIEW DASHBOARD / SUMMARY
-- =========================================================

CREATE VIEW v_performance_review_summary AS
SELECT
    pr.id AS performance_review_id,

    pr.title,
    pr.description,
    pr.start_at,
    pr.end_at,
    pr.status,

    COUNT(ra.id) AS total_assignments,

    COUNT(ra.id)
        FILTER (
            WHERE ra.status = 'NOT_STARTED'
        ) AS not_started,

    COUNT(ra.id)
        FILTER (
            WHERE ra.status = 'DRAFT'
        ) AS draft,

    COUNT(ra.id)
        FILTER (
            WHERE ra.status = 'SUBMITTED'
        ) AS submitted,

    CASE
        WHEN COUNT(ra.id) = 0
            THEN 0

        ELSE ROUND(
            (
                COUNT(ra.id)
                    FILTER (
                        WHERE ra.status = 'SUBMITTED'
                    )::NUMERIC
                /
                COUNT(ra.id)::NUMERIC
            ) * 100,
            2
        )
    END AS completion_percentage,

    pr.closed_at,
    pr.created_at,
    pr.updated_at

FROM performance_reviews pr

LEFT JOIN review_assignments ra
    ON ra.performance_review_id = pr.id

GROUP BY
    pr.id;



-- =========================================================
-- DEFAULT QUESTION TEMPLATE HEADERS
--
-- Pertanyaan belum kita seed karena wording final
-- dapat ditentukan HR.
-- =========================================================

INSERT INTO question_templates (
    name,
    relationship_type,
    description
)
VALUES

(
    'Self Review Template',
    'SELF',
    'Default questions used for self assessment.'
),

(
    'Manager Review Template',
    'MANAGER',
    'Default questions used when a manager reviews an employee.'
),

(
    'Peer Review Template',
    'PEER',
    'Default questions used for peer-to-peer review.'
),

(
    'Subordinate Review Template',
    'SUBORDINATE',
    'Default questions used when a subordinate reviews a manager.'
);


COMMIT;
